# spring.application.name=repositorio_universitario
# spring.datasource.url=jdbc:mysql://localhost:3306/repositorio_universitario
# spring.datasource.username=root
# spring.datasource.password=admin
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enable=true
spring.h2.console.path=/h2-console

server.port=8080
server.servlet.session.persistent=false


spring.security.oauth2.client.registration.google.client-id=798904101516-j8bksfbplacea3cu31dj3q8e4f9smjsp.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
aws.accessKey=${AWS_ACCESS_KEY_ID}
aws.secretKey=${AWS_SECRET_ACCESS_KEY}
aws.region=${AWS_REGION}
aws.s3.bucket=repositorio-universitario-bsi

